### ISSUE TITLE
Crash when putting on armor from MC Dungeon Armor mod

### ISSUE THREAD

**Issue by yoyomattpwns** [apace100/cosmetic-armor#11]
[crash-2022-02-03_15.55.44-client.txt](https://github.com/apace100/cosmetic-armor/files/7998176/crash-2022-02-03_15.55.44-client.txt)
I put on a chestplate from the mod in my cosmetic slot and my game crashed, now every time I try join that server the game crashes and I cannot join.

**Comment by apace100** [comment]
Works fine for me on 1.18.2 with MCDA 2.0.5 and Cosmetic Armor 1.3.0.
I'm going to reopen the issue if you confirm it still exists and upload another crash report.
