### ISSUE TITLE
Crash with Bewitchment armor in cosmetic slot

### ISSUE THREAD

**Issue by MoriyaShiine** [apace100/cosmetic-armor#12]
Version: 1.18-1.2.1

Reported by a user in the discord, https://pastebin.com/7mDaDYZ4

I can only assume that this will also crash with any non-vanilla armor models in the cosmetic slots

**Comment by apace100** [comment]
Can you confirm this still happens with 1.18.2 (version 1.3.0)? I tried to reproduce the bug without luck, using Bewitchment 17.

**Comment by Cytoria** [comment]
> Can you confirm this still happens with 1.18.2 (version 1.3.0)? I tried to reproduce the bug without luck, using Bewitchment 17.

It works perfectly fine. However it does crash if geckolib is present.

**Comment by apace100** [comment]
Fixed with version 1.3.1 of Cosmetic Armor. If the problem persists, let me know and I'll reopen the issue. Sorry for the inconveniences!

**Comment by itsdinkd** [comment]
Can you backport to 1.18.1 please? My modpack, another Quality modpack 2 is still on .1 and plans to be until 1.19. Would help the other modpacks staying on .1 as well.

**Comment by apace100** [comment]
> Can you backport to 1.18.1 please? My modpack, another Quality modpack 2 is still on .1 and plans to be until 1.19. Would help the other modpacks staying on .1 as well.

Done. Let me know if you still have issues.

**Comment by itsdinkd** [comment]
Oh you're a savior. Will check it out tomorrow!
