### ISSUE TITLE
Crashing with custom Mythic Metals Armor rendering

### ISSUE THREAD

**Issue by Noaaan** [apace100/cosmetic-armor#14]
See Noaaan/MythicMetals#72 for crash reports. 

I am not able to re-produce this issue in production, but there is something weird going on with my custom armor rendering (Fabrics ArmorRenderer) and Cosmetic Armor.
 
Some users are reporting crashes despite me not being able to re-produce them. 
I would guess it could happen with the helmets, as your HeadFeatureRendererMixin does not check for custom renderers. 

If you could push the code from latest Cosmetic Armor up to GitHub it would help investigating this issue

**Comment by apace100** [comment]
Sorry for the late response and having forgotten to push the latest code.

I could not reproduce the issue on the latest version of Cosmetic Armor (1.3.0) with Mythic Metals 0.13.1 (on Minecraft 1.18.2).

**Comment by apace100** [comment]
Seems like the problem was an incompatibility with GeckoLib. Fixed this in Cosmetic Armor 1.3.1, so it shouldn't cause any problems anymore if users play with that version of Cosmetic Armor.
