### ISSUE TITLE
Conflicts with one of these mods (maybe you know which one conflicts??)

### ISSUE THREAD

**Issue by KITKATKILLER67** [apace100/cosmetic-armor#16]
i know i have a shit ton of mods here but...

bitsandchisels-2.6.7.jar
293.33 kB
chestcavity-2.15.1.jar
0.99 MB
cloth-config-6.2.57-fabric.jar
1.07 MB
CosmeticArmor-1.18-1.2.0.jar
18.56 kB
diggusmaximus-1.5.4-1.18.jar
208.12 kB
expanded-armor-enchanting-1.0.2.jar
10.21 kB
expanded-trident-enchanting-1.0.3.jar
11.86 kB
fabric-api-0.50.0+1.18.2.jar
1.25 MB
fabric-language-kotlin-1.7.2+kotlin.1.6.20.jar
5.79 MB
FastDecay-1.1.0.jar
18.00 kB
fat-experience-orbs-2.0.0+1.18.1.jar
3.54 kB
lithium-fabric-mc1.18.2-0.7.9.jar
433.30 kB
Pehkui-3.2.1+1.14.4-1.19.jar
334.24 kB
ShowMeWhatYouGot-1.18-1.0.0.jar
25.04 kB
spark-1.8.14-fabric.jar
3.07 MB
starlight-1.0.2+fabric.89b8d9f.jar
124.33 kB
TransparentCosmetics-1.4.0.jar
53.52 kB
trinkets-3.3.0.jar
223.82 kB
worldedit-mod-7.2.10.jar
5.25 MB

Thanks so much you are a really cool person (i just copy/paste this)

If you can tell me which is conflicting that would be appreciated
also if you need me to narrow down the mods i will when i have time
im super busy at the moment
school
i just noticed when i added a couple mods to my server it wouldnt start because of cosmeticarmor
yes i have all the dependencies

**Comment by apace100** [comment]
Do you have a crash report for me? Might help narrow down the culprit.

**Comment by KITKATKILLER67** [comment]
sure

**Comment by KITKATKILLER67** [comment]
https://mclo.gs/eiPx8Va

**Comment by apace100** [comment]
You're trying to run the mod on 1.18.2 - that's not possible with the current version, it only supports up to 1.18.1. Please wait for an update. :)

**Comment by KITKATKILLER67** [comment]
OH!! Sorry XD
