### ISSUE TITLE
Mod applies "Slot: Cosmetic X" tag to every armor piece's lore

### ISSUE THREAD

**Issue by Lucipo** [apace100/cosmetic-armor#2]
It should only apply when you're wearing an armor piece (if ever it should apply) and it affects newly obtained never-worn brand new armor and makes the lore and look of all armor uglier. Please make it toggle able, disable it, or make it only apply to items being worn.

![image](https://user-images.githubusercontent.com/36358294/110048814-2f39c600-7d16-11eb-849f-d1af14d4fa23.png)
![image](https://user-images.githubusercontent.com/36358294/110048829-36f96a80-7d16-11eb-9948-9331366517af.png)

**Comment by apace100** [comment]
AFAIK, Curios didn't really allow to modify the visibility of those tooltips, without mixing into the mod's code at least (which would not be a clean solution).

In the 1.17 update of this mod, which uses the Trinkets API, this was a very clean implementation, thus that version doesn't have any unnecessary tooltips anymore!

(Sorry, but I won't spend the effort to update older Minecraft versions)
